### ISSUE TITLE
feature request:  Export to JSON - PDF.

### ISSUE THREAD

**Issue by tracure1337** [ahmed-zubair-1998/Saveddit#1]
feature request:  Export to JSON - PDF.

That would be really neat.

**Comment by ahmed-zubair-1998** [comment]
For JSON, I could export all the saved posts and subreddits count.
As for PDF, what would you like to be exported?

**Comment by tracure1337** [comment]
@ahmed-zubair-1998  Thanks for looking into this.

All saved posts I think. Not more, not less.

**Comment by Welding-Torch** [comment]
I agree, this would be *insanely* useful.

Information is only really useful when you connect it with other information. Having 'Saved' Posts just sitting in my Reddit isolates them. I'd like to be able to connect my 'Saved' posts with other things.

**Comment by ahmed-zubair-1998** [comment]
Added feature to export saved posts as CSV file as it sounds more intuitive than a PDF file. See #3

**Comment by Welding-Torch** [comment]
I was going through my old email and came across this thread, and I had an idea to export the .csv and load it into Notion Databases, and it works _really well_. In case anyone comes across this, do try it. Definitely a better experience than opening it in Excel.
